# copyright: 2025 European Union
# license: LICENSE.txt
name: cmts_ocean_colour_applications
channels:
  - conda-forge
dependencies:
  # Core
  - conda-forge::python=3.10
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::xarray
  - conda-forge::cartopy
  - conda-forge::scipy
  - conda-forge::netcdf4
  # External
  - eumetsat::eumdac
  # Extension
  - conda-forge::beautifulsoup4
  - conda-forge::cdsapi
  - conda-forge::ephem
  - conda-forge::pandas
  - conda-forge::urllib3
  - conda-forge::ipympl
