# copyright: 2024 European Union
# license: LICENSE.txt
name: cmts_ocean_colour_applications
channels:
  - conda-forge
dependencies:
  # Core
  - conda-forge::python=3.10
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  # External

  # Extension
  - conda-forge::ipympl
  - conda-forge::xcube=1.5
  - conda-forge::copernicusmarine
  - pip
  - pip:
    - eocanvas

