# copyright: 2024 European Union
# license: LICENSE.txt
name: cmts_ocean_colour_applications
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  # Core
#  - conda-forge::bokeh=3.2.1
  - conda-forge::cartopy
  - conda-forge::cmocean
#  - conda-forge::dask
#  - conda-forge::distributed
  - conda-forge::hda
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::netcdf4
  - conda-forge::python=3.10
  - conda-forge::scipy
  - conda-forge::xarray
  # External
  - cmts::eumartools
  - eumetsat::eumdac
  # Extension
  - conda-forge::ipympl
  - conda-forge::joblib
  - conda-forge::pandas
  - conda-forge::requests
#  - conda-forge::rioxarray
  - conda-forge::scikit-image
  - conda-forge::scikit-learn
  - conda-forge::seaborn
#  - conda-forge::shapely
  - conda-forge::spectral  
  - conda-forge::tensorflow
  - conda-forge::tensorflow-probability
  - conda-forge::tqdm
  - conda-forge::xmltodict