## ACOLITE settings
## Written at 2025-11-17 15:05:42
polygon=None
atmospheric_correction=True
atmospheric_correction_method=dark_spectrum
tact_run=False
l2w_parameters=Rrs_*,chl_oc2,chl_oc3,spm_nechad2016,qaa_v6_bbp_443,qaa_v6_a_443
rgb_rhot=False
rgb_rhos=False
map_l2w=False
s2_target_res=60